### PR TITLE
#184469812 : reducing write contention to user/company ID

### PR DESCRIPTION
**Pull request by bakennedy**
When in debug mode AND the log level is set to debug, output log messages about these variables.

### CODE REVIEW

**Review by praves77 — APPROVED** [review]
lftm

**Comment by praves77** [comment]
@bakennedy don't we have version for the plugin ?

**Review by dgilling — APPROVED** [review]

**Comment by bakennedy** [comment]
What's wrong with my PR?  I can't push up the version update commit, getting a sync error from vs code
@praves77 @dgilling

**Comment by bakennedy** [comment]
For future reference, this is the Dockerfile used to make and test this locally:
```
FROM kong:2.1.3-ubuntu

USER root
WORKDIR /build

# Copy the Kong configuration file
COPY kong.conf /etc/kong/kong.conf
COPY kong.yml /etc/kong/kong.yml

COPY kong /build/kong
COPY kong-plugin-moesif-2.0.2-1.rockspec /build/

RUN luarocks make kong-plugin-moesif-2.0.2-1.rockspec

USER kong
```

**Pull request merged**
